'use client';

import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Database, Copy, Server, Cpu, Save } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';

export default function PgConfigGeneratorClient() {
    const [totalRam, setTotalRam] = useState(16); // GB
    const [cpus, setCpus] = useState(4);
    const [connections, setConnections] = useState(100);
    const [dbType, setDbType] = useState('WEB'); // WEB, OLTP, DW, DESKTOP, MIXED
    const [pgVersion, setPgVersion] = useState('16');
    const [config, setConfig] = useState('');
    const { toast } = useToast();

    useEffect(() => {
        generateConfig();
    }, [totalRam, cpus, connections, dbType, pgVersion]);

    const generateConfig = () => {
        // Simplified PGTune Logic
        const memInKb = totalRam * 1024 * 1024;

        let sharedBuffersRatio = 0.25;
        let effectiveCacheRatio = 0.75;
        let maintenanceWorkMemRatio = 0.05; // max 2GB usually
        let workMemRatio = 0; // per connection calculation

        if (dbType === 'DW') {
            sharedBuffersRatio = 0.25;
            effectiveCacheRatio = 0.75;
            workMemRatio = 0.05; // aggressively higher for complex queries
        } else if (dbType === 'OLTP') {
            sharedBuffersRatio = 0.25;
            effectiveCacheRatio = 0.75;
        } else if (dbType === 'WEB') {
            sharedBuffersRatio = 0.25;
            effectiveCacheRatio = 0.75;
        } else if (dbType === 'DESKTOP') {
            sharedBuffersRatio = 0.10;
            effectiveCacheRatio = 0.50;
        }

        const sharedBuffers = Math.floor(memInKb * sharedBuffersRatio);
        const effectiveCacheSize = Math.floor(memInKb * effectiveCacheRatio);
        const maintenanceWorkMem = Math.min(Math.floor(memInKb * maintenanceWorkMemRatio), 2 * 1024 * 1024); // Cap at 2GB

        // work_mem calculation: (Total RAM - Shared Buffers) / (max_connections * 3)
        // 3 is mostly an estimation for parallel queries or complex nodes
        const availableForWorkMem = memInKb - sharedBuffers;
        const workMem = Math.floor(availableForWorkMem / (connections * 3));

        // Format: size in kB, MB, GB
        const formatSize = (kb: number) => {
            if (kb > 1024 * 1024) return `${Math.floor(kb / (1024 * 1024))}GB`;
            if (kb > 1024) return `${Math.floor(kb / 1024)}MB`;
            return `${Math.floor(kb)}kB`;
        };

        const conf = [
            `# PostgreSQL ${pgVersion} Configuration`,
            `# Generated by Tool Daddy`,
            `# System: ${totalRam}GB RAM, ${cpus} Cores, ${dbType} Workload`,
            ``,
            `max_connections = ${connections}`,
            `shared_buffers = ${formatSize(sharedBuffers)}`,
            `effective_cache_size = ${formatSize(effectiveCacheSize)}`,
            `maintenance_work_mem = ${formatSize(maintenanceWorkMem)}`,
            `checkpoint_completion_target = 0.9`,
            `wal_buffers = 16MB`,
            `default_statistics_target = 100`,
            `random_page_cost = 1.1`,
            `effective_io_concurrency = 200`,
            `work_mem = ${formatSize(workMem)}`,
            `min_wal_size = 1GB`,
            `max_wal_size = 4GB`,
            `max_worker_processes = ${cpus}`,
            `max_parallel_workers_per_gather = ${Math.max(2, Math.floor(cpus / 2))}`,
            `max_parallel_workers = ${cpus}`,
            `max_parallel_maintenance_workers = ${Math.max(2, Math.floor(cpus / 2))}`,
        ].join('\n');

        setConfig(conf);
    };

    const copyToClipboard = () => {
        navigator.clipboard.writeText(config);
        toast({ title: 'Config copied to clipboard' });
    };

    return (
        <div className="container mx-auto py-10 px-4 max-w-7xl">
            <div className="flex flex-col items-center mb-10 text-center">
                <div className="p-4 rounded-2xl bg-primary/10 mb-4">
                    <Database className="h-10 w-10 text-primary" />
                </div>
                <h1 className="text-4xl font-bold font-headline mb-2">PostgreSQL Config Generator</h1>
                <p className="text-muted-foreground">Generate optimized configuration for your PostgreSQL database.</p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-12 gap-8">
                {/* Inputs */}
                <Card className="glass-panel border-primary/20 md:col-span-4 h-fit">
                    <CardHeader>
                        <CardTitle className="text-lg">System Resources</CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        <div className="space-y-2">
                            <Label>DB Version</Label>
                            <Select value={pgVersion} onValueChange={setPgVersion}>
                                <SelectTrigger><SelectValue /></SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="16">16</SelectItem>
                                    <SelectItem value="15">15</SelectItem>
                                    <SelectItem value="14">14</SelectItem>
                                    <SelectItem value="13">13</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>

                        <div className="space-y-2">
                            <Label>OS Type</Label>
                            <Select defaultValue="Linux">
                                <SelectTrigger><SelectValue /></SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="Linux">Linux</SelectItem>
                                    <SelectItem value="Windows">Windows</SelectItem>
                                    <SelectItem value="MacOS">MacOS</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>

                        <div className="space-y-2">
                            <Label>DB Type</Label>
                            <Select value={dbType} onValueChange={setDbType}>
                                <SelectTrigger><SelectValue /></SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="WEB">Web Application</SelectItem>
                                    <SelectItem value="OLTP">Online Transaction Processing</SelectItem>
                                    <SelectItem value="DW">Data Warehouse</SelectItem>
                                    <SelectItem value="DESKTOP">Desktop Application</SelectItem>
                                    <SelectItem value="MIXED">Mixed Application</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>

                        <div className="space-y-2">
                            <div className="flex justify-between">
                                <Label>Total RAM (GB)</Label>
                                <span className="font-mono text-xs">{totalRam} GB</span>
                            </div>
                            <Input
                                type="number"
                                value={totalRam}
                                onChange={(e) => {
                                    const v = Number(e.target.value);
                                    setTotalRam(v > 1024 ? 1024 : v < 0 ? 0 : v);
                                }}
                            />
                        </div>

                        <div className="space-y-2">
                            <div className="flex justify-between">
                                <Label>Number of CPUs</Label>
                                <span className="font-mono text-xs">{cpus} Cores</span>
                            </div>
                            <Input
                                type="number"
                                value={cpus}
                                onChange={(e) => {
                                    const v = Number(e.target.value);
                                    setCpus(v > 512 ? 512 : v < 1 ? 1 : v);
                                }}
                            />
                        </div>

                        <div className="space-y-2">
                            <div className="flex justify-between">
                                <Label>Number of Connections</Label>
                                <span className="font-mono text-xs">{connections}</span>
                            </div>
                            <Input
                                type="number"
                                value={connections}
                                onChange={(e) => {
                                    const v = Number(e.target.value);
                                    setConnections(v > 100000 ? 100000 : v < 1 ? 1 : v);
                                }}
                            />
                        </div>
                    </CardContent>
                </Card>

                {/* Output */}
                <Card className="glass-panel border-primary/20 md:col-span-8 flex flex-col h-[600px]">
                    <CardHeader className="flex flex-row items-center justify-between pb-4">
                        <CardTitle className="text-lg font-medium">postgresql.conf</CardTitle>
                        <Button variant="ghost" size="sm" onClick={copyToClipboard}>
                            <Copy className="w-4 h-4 mr-2" /> Copy
                        </Button>
                    </CardHeader>
                    <CardContent className="flex-1 flex flex-col min-h-0">
                        <Textarea
                            readOnly
                            className="flex-1 font-mono text-sm resize-none bg-background/50 leading-relaxed"
                            value={config}
                        />
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
